spring:
  env:
    baseUrl: http://localhost:8080/api/v1/shortener
  application:
    name: shorter
  datasource:
    url: jdbc:h2:mem:shortener-db
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
      show-sql: true
    h2:
      console:
        enabled: true
        path: /h2-console
        settings.trace: false
        settings.web-allow-others: false
    flyway:
      enabled: true
      locations: classpath:db/migration/structure, classpath:db/migration/data
